apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis-master-pvc
  namespace: gitfolio
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis-slave-pvc
  namespace: gitfolio
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi