apiVersion: v1
kind: Service
metadata:
  name: redis-auth-service    # ConfigMap에 정의된 AUTH_REDIS_HOST와 일치
  namespace: gitfolio
  labels:
    app: redis
spec:
  selector:
    app: redis
  type: ClusterIP
  ports:
    - name: redis
      port: 6379
      targetPort: 6379
      protocol: TCP

---
apiVersion: v1
kind: Service
metadata:
  name: redis-resume-service  # ConfigMap에 정의된 RESUME_REDIS_HOST와 일치
  namespace: gitfolio
  labels:
    app: redis
spec:
  selector:
    app: redis
  type: ClusterIP
  ports:
    - name: redis
      port: 6379
      targetPort: 6379
      protocol: TCP