architecture: replication

auth:
  enabled: false

master:
  persistence:
    enabled: true
    storageClass: gitfolio-redis-sc
    accessModes:
      - ReadWriteOnce
    size: 2Gi
  affinity:
    podAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
      - labelSelector:
          matchExpressions:
            - key: app.kubernetes.io/instance
              operator: In
              values:
              - gitfolio-redis
            - key: app.kubernetes.io/name
              operator: In
              values:
              - redis
        topologyKey: kubernetes.io/hostname
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
            - key: node-role.kubernetes.io/db
              operator: Exists

replica:
  replicaCount: 3
  persistence:
    enabled: true
    storageClass: gitfolio-redis-sc
    accessModes:
      - ReadWriteOnce
    size: 2Gi
  affinity:
    podAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
      - labelSelector:
          matchExpressions:
            - key: app.kubernetes.io/instance
              operator: In
              values:
              - gitfolio-redis
            - key: app.kubernetes.io/name
              operator: In
              values:
              - redis
        topologyKey: kubernetes.io/hostname
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
            - key: node-role.kubernetes.io/db
              operator: Exists

metrics:
  enabled: true
  service:
    annotations:
      prometheus.io/scrape: "true"
      prometheus.io/port: "9121"

# 자동으로 fail over 지원
sentinel:
  enabled: true
  quorum: 2
  getMaterTimeout: 10