# member-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: member-service
  namespace: gitfolio
  labels:
    app: member
spec:
  selector:
    app: member
  type: ClusterIP
  ports:
    - name: http
      port: 81            # 파드가 개방하는 포트
      targetPort: 8080    # 앱이 리스닝하는 포트 
      protocol: TCP
    - name: https
      port: 444
      targetPort: 8080
      protocol: TCP