apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-deployment
  namespace: gitfolio
  labels:
    app: kafka
spec:
  replicas: 3
  selector:
    matchLabels:
      app: kafka
  template:
    metadata:
      labels:
        app: kafka
    spec:
      containers:
        - name: kafka
          image: confluentinc/cp-kafka:7.4.0
          ports:
            - name: kafka1
              containerPort: 9092
            - name: kafka2
              containerPort: 29092
          envFrom:
            - configMapRef:
                name: backend-configmap