apiVersion: v1
kind: Service
metadata:
  name: mongo-member-service  # Secret에 정의된 MEMBER_MONGO_DB_HOST와 일치
  namespace: gitfolio
  labels:
    app: mongodb
spec:
  selector:
    app: mongodb
  type: ClusterIP
  ports:
    - name: mongo
      port: 27017
      targetPort: 27017
      protocol: TCP

---
apiVersion: v1
kind: Service
metadata:
  name: mongo-resume-service  # Secret에 정의된 RESUME_MONGO_DB_HOST와 일치
  namespace: gitfolio
  labels:
    app: mongodb
spec:
  selector:
    app: mongodb
  type: ClusterIP
  ports:
    - name: mongo
      port: 27017
      targetPort: 27017
      protocol: TCP

---
apiVersion: v1
kind: Service
metadata:
  name: mongo-chat-service    # Secret에 정의된 CHAT_MONGO_DB_HOST와 일치
  namespace: gitfolio
  labels:
    app: mongodb
spec:
  selector:
    app: mongodb
  type: ClusterIP
  ports:
    - name: mongo
      port: 27017
      targetPort: 27017
      protocol: TCP