global:
  namespace: gitfolio

image:
  registry: docker.io
  repository: bitnami/mongodb
  tag: 4.4.4-debian-10-r41
  pullPolicy: IfNotPresent

architecture: replicaset
replicaCount: 3

arbiter:
  enabled: false

persistence:
  size: 2Gi

service:
  type: ClusterIP
  port: 27017

metrics:
  enabled: true

primary:
  persistence:
    size: 2Gi
    mountPath: /data/mongodb
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: node-role.kubernetes.io/db
            operator: Exists

secondary:
  persistence:
    size: 2Gi
    mountPath: /data/mongodb
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: node-role.kubernetes.io/db
            operator: Exists

podAntiAffinity:
  requiredDuringSchedulingIgnoredDuringExecution:
  - labelSelector:
      matchExpressions:
      - key: app.kubernetes.io/instance
        operator: In
        values:
        - gitfolio-mongo
      - key: app.kubernetes.io/component
        operator: In
        values:
        - mongodb
    topologyKey: kubernetes.io/hostname