apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongodb-master-statefulset
  namespace: gitfolio
  labels:
    app: mongodb-master
spec:
  replicas: 1
  serviceName: mongodb-master
  selector:
    matchLabels:
      app: mongodb-master
  template:
    metadata:
      labels:
        app: mongodb-master
    spec:
      containers:
        - name: mongodb-master
          image: mongo:latest
          ports:
            - containerPort: 27017
          volumeMounts:
            - name: mongodb-master-pvc
              mountPath: /data/db
          # ConfigMap과 Secret에서 환경변수 가져오기
          envFrom:
            - configMapRef:
                name: backend-configmap
            - secretRef:
                name: backend-secret
          # resources:
          #   requests:
          #     memory: "1Gi"
          #     cpu: "500m"
          #   limits:
          #     memory: "2Gi"
          #     cpu: "1000m"
      volumes:
        - name: mongodb-master-pvc
          persistentVolumeClaim:
            claimName: mongodb-master-pvc
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongodb-slave-statefulset
  namespace: gitfolio
  labels:
    app: mongodb-slave
spec:
  replicas: 1
  serviceName: mongodb-slave
  selector:
    matchLabels:
      app: mongodb-slave
  template:
    metadata:
      labels:
        app: mongodb-slave
    spec:
      containers:
        - name: mongodb-slave
          image: mongo:latest
          ports:
            - containerPort: 27017
          volumeMounts:
            - name: mongodb-slave-pvc
              mountPath: /data/db
          # ConfigMap과 Secret에서 환경변수 가져오기
          envFrom:
            - configMapRef:
                name: backend-configmap
            - secretRef:
                name: backend-secret
          # resources:
          #   requests:
          #     memory: "1Gi"
          #     cpu: "500m"
          #   limits:
          #     memory: "2Gi"
          #     cpu: "1000m"
      volumes:
        - name: mongodb-slave-pvc
          persistentVolumeClaim:
            claimName: mongodb-slave-pvc