apiVersion: v1
kind: PersistentVolume
metadata:
  name: gitfolio-mongo-pv-1
spec:
  accessModes:
    - ReadWriteOnce    # 단일 노드에서만 읽기/쓰기 가능
  capacity:
    storage: 2Gi    # PVC와 동일한 크기로 설정
  volumeMode: Filesystem
  persistentVolumeReclaimPolicy: Delete    # PVC가 삭제되어도 데이터 유지
  hostPath:
    path: /data/mongodb    # 호스트 시스템의 경로
    type: DirectoryOrCreate    # 디렉토리가 없으면 자동 생성
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: node-role.kubernetes.io/db
          operator: In
          values:
          - ip-10-0-103-8.ap-northeast-2.compute.internal
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: gitfolio-mongo-pv-2
spec:
  accessModes:
    - ReadWriteOnce    # 단일 노드에서만 읽기/쓰기 가능
  capacity:
    storage: 2Gi    # PVC와 동일한 크기로 설정
  volumeMode: Filesystem
  persistentVolumeReclaimPolicy: Delete    # PVC가 삭제되어도 데이터 유지
  hostPath:
    path: /data/mongodb    # 호스트 시스템의 경로
    type: DirectoryOrCreate    # 디렉토리가 없으면 자동 생성
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: node-role.kubernetes.io/db
          operator: In
          values:
          - ip-10-0-103-9.ap-northeast-2.compute.internal
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: gitfolio-mongo-pv-3
spec:
  accessModes:
    - ReadWriteOnce    # 단일 노드에서만 읽기/쓰기 가능
  capacity:
    storage: 2Gi    # PVC와 동일한 크기로 설정
  volumeMode: Filesystem
  persistentVolumeReclaimPolicy: Delete    # PVC가 삭제되어도 데이터 유지
  hostPath:
    path: /data/mongodb    # 호스트 시스템의 경로
    type: DirectoryOrCreate    # 디렉토리가 없으면 자동 생성
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: node-role.kubernetes.io/db
          operator: In
          values:
          - ip-10-0-103-10.ap-northeast-2.compute.internal