apiVersion: v1
kind: Service
metadata:
  name: gitfolio-mongo-member-service  # Secret에 정의된 MEMBER_MONGO_DB_HOST와 일치
  namespace: gitfolio-mongo
  labels:
    app.kubernetes.io/component: mongodb
    app.kubernetes.io/instance: gitfolio-mongo
    app.kubernetes.io/name: mongodb
spec:
  selector:
    app.kubernetes.io/component: mongodb
    app.kubernetes.io/instance: gitfolio-mongo
    app.kubernetes.io/name: mongodb
  type: ClusterIP
  ports:
    - name: mongo
      port: 27017
      targetPort: 27017
      protocol: TCP

---
apiVersion: v1
kind: Service
metadata:
  name: gitfolio-mongo-resume-service  # Secret에 정의된 RESUME_MONGO_DB_HOST와 일치
  namespace: gitfolio-mongo
  labels:
    app.kubernetes.io/component: mongodb
    app.kubernetes.io/instance: gitfolio-mongo
    app.kubernetes.io/name: mongodb
spec:
  selector:
    app.kubernetes.io/component: mongodb
    app.kubernetes.io/instance: gitfolio-mongo
    app.kubernetes.io/name: mongodb
  type: ClusterIP
  ports:
    - name: mongo
      port: 27017
      targetPort: 27017
      protocol: TCP

---
apiVersion: v1
kind: Service
metadata:
  name: gitfolio-mongo-chat-service    # Secret에 정의된 CHAT_MONGO_DB_HOST와 일치
  namespace: gitfolio-mongo
  labels:
    app.kubernetes.io/component: mongodb
    app.kubernetes.io/instance: gitfolio-mongo
    app.kubernetes.io/name: mongodb
spec:
  selector:
    app.kubernetes.io/component: mongodb
    app.kubernetes.io/instance: gitfolio-mongo
    app.kubernetes.io/name: mongodb
  type: ClusterIP
  ports:
    - name: mongo
      port: 27017
      targetPort: 27017
      protocol: TCP