# backend-configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: gitfolio-backend-configmap
  namespace: gitfolio-back
data:
  # 서비스 URL 설정
  REDIRECT_ONBOARDING_URL: https://www.gitfolio.site/onboarding
  REDIRECT_MAIN_URL: https://www.gitfolio.site/community
  PAYMENT_SUCCESS_REDIRECT_URL: https://www.gitfolio.site/plan/success

  MEMBER_SERVER_URL: http://gitfolio-member-service
  PAYMENTS_SERVER_URL: http://gitfolio-payment-service
  NOTIFICATIONS_SERVER_URL: http://gitfolio-notification-service
  AI_SERVER_URL: http://gitfolio-ai-service

  # 서비스 포트 설정
  MEMBER_GRPC_PORT: "9090"
  AUTH_SERVER_PORT: "8080"
  MEMBER_SERVER_PORT: "8080"
  RESUME_SERVER_PORT: "8080"
  PAYMENT_SERVER_PORT: "8080"
  NOTIFICATION_SERVER_PORT: "8080"
  CHAT_SERVER_PORT: "8080"

  # Github OAuth 2.0
  GH_REDIRECT_URI: https://www.gitfolio.site/login/oauth2/code/github

  # REDIS 설정
  AUTH_REDIS_HOST: gitfolio-redis-auth-service
  AUTH_REDIS_PORT: "6379"

  RESUME_REDIS_HOST: gitfolio-redis-resume-service
  RESUME_REDIS_PORT: "6379"

  # MySQL 설정
  MEMBER_MYSQL_DB_HOST: gitfolio-mysql.c9mu608uomlm.ap-northeast-2.rds.amazonaws.com
  MEMBER_MYSQL_DB_PORT: "3306"
  MEMBER_MYSQL_DB_NAME: gitfolio_member

  RESUME_MYSQL_DB_HOST: gitfolio-mysql.c9mu608uomlm.ap-northeast-2.rds.amazonaws.com
  RESUME_MYSQL_DB_PORT: "3306"
  RESUME_MYSQL_DB_NAME: gitfolio_resume

  PAYMENT_MYSQL_DB_HOST: gitfolio-mysql.c9mu608uomlm.ap-northeast-2.rds.amazonaws.com
  PAYMENT_MYSQL_DB_PORT: "3306"
  PAYMENT_MYSQL_DB_NAME: gitfolio_payment

  NOTIFICATION_MYSQL_DB_HOST: gitfolio-mysql.c9mu608uomlm.ap-northeast-2.rds.amazonaws.com
  NOTIFICATION_MYSQL_DB_PORT: "3306"
  NOTIFICATION_MYSQL_DB_NAME: gitfolio_notification

  # MongoDB 설정
  MEMBER_MONGO_DB_USERNAME: gitfolio-mongo-member-service
  MEMBER_MONGO_DB_PORT: "27017"
  MEMBER_MONGO_DB_DATABASE: gitfolio_member

  RESUME_MONGO_DB_USERNAME: gitfolio-mongo-resume-service
  RESUME_MONGO_DB_PORT: "27017"
  RESUME_MONGO_DB_DATABASE: gitfolio_resume

  CHAT_MONGO_DB_USERNAME: gitfolio-mongo-chat-service
  CHAT_MONGO_DB_PORT: "27017"
  CHAT_MONGO_DB_DATABASE: gitfolio_chat

  # S3
  S3_URL_PREFIX: https://gitfolio.s3.amazonaws.com/

  # Kakao Pay
  KAKAO_API_URL: https://open-api.kakaopay.com/online/v1/payment

  # Kafka 설정
  KAFKA_HOST1: gitfolio-kafka-service
  KAFKA_PORT1: "9092"

  KAFKA_BROKER_ID: "1"
  KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181

  KAFKA_LISTENER_DOCKER: PLAINTEXT://0.0.0.0:29092
  KAFKA_LISTENER_EXTERNAL: PLAINTEXT://0.0.0.0:9092

  KAFKA_ADVERTISED_LISTENER_DOCKER: PLAINTEXT://localhost:29092
  KAFKA_ADVERTISED_LISTENER_EXTERNAL: PLAINTEXT://10.0.105.99:9092

  KAFKA_INTER_BROKER_LISTENER_NAME: LISTENER_DOCKER
  KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: "1"