apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  namespace: default
  labels:
    app: frontend
spec:
  replicas: 2  # 고가용성을 위해 2개의 레플리카 추천
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: aida0/gitfolio_front:test
          ports:
            - containerPort: 3000
          # ConfigMap과 Secret에서 환경변수 가져오기
          envFrom:
            - configMapRef:
                name: frontend-configmap
            - secretRef:
                name: frontend-secret
          resources:
            requests:
              memory: "256Mi"
              cpu: "200m"
            limits:
              memory: "512Mi"
              cpu: "500m"
#추후 헬스체크 추가시 구현필요