apiVersion: apps/v1
kind: Deployment
metadata:
  name: gitfolio-ai-deployment
  namespace: gitfolio
  labels:
    app: gitfolio-ai
spec:
  replicas: 1 # 고가용성을 위해 2개의 레플리카 설정
  selector:
    matchLabels:
      app: gitfolio-ai
  template:
    metadata:
      labels:
        app: gitfolio-ai
    spec:
      imagePullSecrets:
        - name: gitfolio-container-registry
      containers:
        - name: gitfolio-ai
          image: 727646500036.dkr.ecr.ap-northeast-2.amazonaws.com/gitfolio/ai:prod
          ports:
            - containerPort: 8000
          envFrom:
            - configMapRef:
                name: gitfolio-ai-configmap
            - secretRef:
                name: gitfolio-ai-secret
          resources:
            requests:
              memory: "256Mi"
              cpu: "200m"
            limits:
              memory: "512Mi"
              cpu: "500m"
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: app
                    operator: In
                    values:
                      - gitfolio-ai
              topologyKey: kubernetes.io/hostname
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: node-role.kubernetes.io/worker
                    operator: Exists
