apiVersion: v1
kind: Service
metadata:
  name: ai-service
  namespace: gitfolio
  labels:
    app: ai
spec:
  type: LoadBalancer
  ports:
    - name: http
      port: 80
      targetPort: 8000
      protocol: TCP
    - name: https
      port: 443
      targetPort: 8000
      protocol: TCP
  selector:
    app: ai