apiVersion: v1
kind: Service
metadata:
  name: gitfolio-ai-service
  namespace: gitfolio-ai
  labels:
    app: gitfolio-ai
spec:
  selector:
    app: gitfolio-ai
  type: ClusterIP
  ports:
    - name: http
      port: 80
      targetPort: 8000
      protocol: TCP
    - name: https
      port: 443
      targetPort: 8000
      protocol: TCP