apiVersion: v1
kind: ConfigMap
metadata:
  name: frontend-configmap
  namespace: default
data:
  # 공개적으로 접근 가능한 URL들은 ConfigMap에 저장
  NEXT_PUBLIC_API_URL: "https://www.gitfolio.site"
  # 내부 서비스 URL들은 쿠버네티스 서비스 이름으로 변경
  AUTH_SERVER_URL: "http://auth-service:8080"
  MEMBERS_SERVER_URL: "http://member-service:8080"
  RESUMES_SERVER_URL: "http://resume-service:8080"
  PAYMENTS_SERVER_URL: "http://payment-service:8080"
  NOTIFICATIONS_SERVER_URL: "http://notification-service:8080"
#  추후 채팅 구현 대비
  CHAT_SERVER_URL: "http://chat-service:8080"