apiVersion: apps/v1
kind: Deployment
metadata:
  name: gitfolio-back-auth-deployment
  namespace: gitfolio
  labels:
    app: gitfolio-auth
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gitfolio-auth
  template:
    metadata:
      labels:
        app: gitfolio-auth
    spec:
      imagePullSecrets:
        - name: gitfolio-container-registry
      containers:
        - name: gitfolio-auth
          image: 727646500036.dkr.ecr.ap-northeast-2.amazonaws.com/gitfolio/auth:prod
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: gitfolio-back-configmap
            - secretRef:
                name: gitfolio-back-secret
          resources:
            requests:
              memory: "256Mi"
              cpu: "200m"
            limits:
              memory: "512Mi"
              cpu: "500m"
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: app
                    operator: In
                    values:
                      - gitfolio-auth
              topologyKey: kubernetes.io/hostname
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: node-role.kubernetes.io/worker
                    operator: Exists
