apiVersion: apps/v1
kind: Deployment
metadata:
  name: gitfolio-resume-deployment
  namespace: gitfolio-back
  labels:
    app: gitfolio-resume
spec:
  replicas: 3
  selector:
    matchLabels:
      app: gitfolio-resume
  template:
    metadata:
      labels:
        app: gitfolio-resume
    spec:
      containers:
        - name: gitfolio-resume
          image: aida0/gitfolio_resume:test
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: backend-configmap
            - secretRef:
                name: backend-secret
          # resources:
          #   requests:
          #     memory: "512Mi"
          #     cpu: "300m"
          #   limits:
          #     memory: "1Gi"
          #     cpu: "600m"