- name: Configure Kubernetes master node
  hosts: k8s_master
  tasks:
    - name: Update kubeadm images
      shell: |
        kubeadm config images pull

    - name: Initialize Kubernetes cluster
      shell: |
        kubeadm init --apiserver-advertise-address={{ ansible_master_host }} --pod-network-cidr={{ ansible_pod_network_cidr }}
      args:
        creates: /etc/kubernetes/admin.conf
    
    - name: Create .kube directory
      file:
        path: "{{ ansible_home_dir }}/.kube"
        state: directory

    - name: Copy admin.conf to root's kube config
      copy:
        src: /etc/kubernetes/admin.conf
        dest: "{{ ansible_home_dir }}/.kube/config"
        remote_src: yes
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
        mode: '0600'
    
    - name: Change default namespace to gitfolio
      shell: |
        kubectl config set-context --current --namespace={{ ansible_helm_charts[2].namespace }}

    - name: Install Python3 Kubernetes module
      pip:
        name: kubernetes
        state: present

    - name: Copy kube config for local use
      copy:
        src: "{{ ansible_home_dir }}/.kube/config"
        dest: "{{ ansible_home_dir }}/.kube/local"
        remote_src: yes
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
        mode: '0600'

    - name: Insert tls certificate skip
      lineinfile:
        path: "{{ ansible_home_dir }}/.kube/local"
        insertafter: "^.*certificate-authority-data:.*"
        line: "    insecure-skip-tls-verify: true"

    - name: Erase certificate authority data
      replace:
        path: "{{ ansible_home_dir }}/.kube/local"
        regexp: "^.*certificate-authority-data:.*"
        replace: '# \g<0>'

    - name: Erase certificate authority data
      replace:
        path: "{{ ansible_home_dir }}/.kube/local"
        regexp: "10.0.103.6"
        replace: "localhost"

    - name: Copy admin.conf to local directory
      fetch:
        src: "{{ ansible_home_dir }}/.kube/temp"
        dest: ~/.kube/config
        mode: '0600'
        flat: yes

    - name: Delete temp config
      file:
        path: "{{ ansible_home_dir }}/.kube/temp"
        state: absent