- name: Configure Kubernetes master node
  hosts: helm
  tasks:
    - name: Download Helm install script
      get_url:
        url: https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3
        dest: /tmp/get_helm.sh
        mode: '0700'

    - name: Execute Helm installation script
      shell: |
        /tmp/get_helm.sh
    
    - name: Add helm charts 
      become: no
      kubernetes.core.helm_repository:
        name: "{{ item.name }}"
        repo_url: "{{ item.repo_url }}"
      loop: "{{ ansible_helm_charts[:5] }}"

    - name: Deploy Calico System
      become: no
      kubernetes.core.helm:
        kubeconfig: "{{ ansible_home_dir }}/.kube/config"
        name: "{{ ansible_helm_charts[0].name }}"
        chart_ref: "{{ ansible_helm_charts[0].chart_ref }}"
        release_namespace: "{{ ansible_helm_charts[0].namespace }}"
        create_namespace: true

    # - name: Deploy Helm charts
    #   become: no
    #   kubernetes.core.helm:
    #     kubeconfig: "{{ ansible_home_dir }}/.kube/config"
    #     name: "{{ item.name }}"
    #     chart_ref: "{{ item.chart_ref }}"
    #     release_namespace: "{{ item.namespace }}"
    #     create_namespace: true
    #   loop: "{{ ansible_helm_charts[1:] }}"